### ISSUE TITLE
Generar tabla de productos

### ISSUE THREAD

**Issue by rburdet** [NickCis/my-pet#1]

**Comment by NickCis** [comment]
Para que la tabla la cree con `npm run setup`, tenes que agregar el ddl en el archivo [`server/db.js` en la función `create`](https://github.com/NickCis/my-pet/blob/master/server/db.js#L84).

Ponelo como siguiente item en el array y te lo debería crear (usa `CREATE TABLE IF NOT EXISTS`, asi no falla si la tabla ya existe)

**Comment by rburdet** [comment]
=') lo termine de resolver anoche pero me olvide #closearlo
